insert into dbo.product_cn_en_contrast values('90度长径弯头', '90°Long Radius Elbows')
insert into dbo.product_cn_en_contrast values('90度短径弯头', '90°Short Radius Elbows')
insert into dbo.product_cn_en_contrast values('45度长径弯头', '45°Long Radius Elbows')
insert into dbo.product_cn_en_contrast values('180度弯头', '180°Long Radius Elbows')
insert into dbo.product_cn_en_contrast values('同心大小头', 'Concentric Reducers')
insert into dbo.product_cn_en_contrast values('偏心大小头', 'Eccentric Reducers')
insert into dbo.product_cn_en_contrast values('等径三通', 'Equal Tees')
insert into dbo.product_cn_en_contrast values('异径三通', 'Reducing Tees')
insert into dbo.product_cn_en_contrast values('翻边 A型', 'Stub Ends Type A')
insert into dbo.product_cn_en_contrast values('翻边 B型', 'Stub Ends Type B')
insert into dbo.product_cn_en_contrast values('管帽', 'Caps')